FROM kolla/ubuntu-binary-nova-base:8.0.0
LABEL maintainer="Kolla Project (https://launchpad.net/kolla)" name="nova-mksproxy" build-date="20190404"






RUN echo 'binary not yet available for ubuntu' && /bin/false




USER nova