FROM kolla/ubuntu-binary-novajoin-base:8.0.0
LABEL maintainer="Kolla Project (https://launchpad.net/kolla)" name="novajoin-server" build-date="20190404"






    
RUN echo 'binary not yet available for ubuntu' \
    && /bin/false
    



