FROM kolla/ubuntu-binary-heat-base:8.0.0
LABEL maintainer="Kolla Project (https://launchpad.net/kolla)" name="heat-all" build-date="20190404"






    
RUN echo 'heat-all not yet available for ubuntu' && /bin/false
    






USER heat