FROM kolla/ubuntu-binary-senlin-base:8.0.0
LABEL maintainer="Kolla Project (https://launchpad.net/kolla)" name="senlin-engine" build-date="20190404"






    
        
    

RUN apt-get update && apt-get -y install --no-install-recommends senlin-engine && apt-get clean && rm -rf /var/lib/apt/lists/*






USER senlin