FROM kolla/ubuntu-binary-karbor-base:8.0.0
LABEL maintainer="Kolla Project (https://launchpad.net/kolla)" name="karbor-operationengine" build-date="20190404"





RUN echo 'binary not yet available for ubuntu' \
    && /bin/false






USER karbor