FROM kolla/ubuntu-binary-blazar-base:8.0.0
LABEL maintainer="Kolla Project (https://launchpad.net/kolla)" name="blazar-manager" build-date="20190404"





RUN echo 'binary not yet available for ubuntu' \
    && /bin/false






USER blazar