FROM kolla/ubuntu-binary-zaqar-base:8.0.0
LABEL maintainer="Kolla Project (https://launchpad.net/kolla)" name="zaqar-server" build-date="20190404"






    
        

RUN apt-get update && apt-get -y install --no-install-recommends zaqar-server && apt-get clean && rm -rf /var/lib/apt/lists/*

    



