FROM kolla/ubuntu-binary-ceph-base:8.0.0
LABEL maintainer="Kolla Project (https://launchpad.net/kolla)" name="ceph-osd" build-date="20190404"



COPY extend_start.sh /usr/local/bin/kolla_extend_start
RUN chmod 755 /usr/local/bin/kolla_extend_start


