FROM kolla/ubuntu-binary-monasca-base:8.0.0
LABEL maintainer="Kolla Project (https://launchpad.net/kolla)" name="monasca-notification" build-date="20190404"







RUN echo 'binary not yet available for ubuntu' \
    && /bin/false







USER monasca
