FROM kolla/ubuntu-binary-tacker-base:8.0.0
LABEL maintainer="Kolla Project (https://launchpad.net/kolla)" name="tacker-conductor" build-date="20190404"







    

RUN echo 'binary not yet available for ubuntu' \
    && /bin/false

    








USER tacker