FROM kolla/ubuntu-binary-cyborg-base:8.0.0
LABEL maintainer="Kolla Project (https://launchpad.net/kolla)" name="cyborg-agent" build-date="20190404"






RUN echo 'binary not yet available for ubuntu'  \
    && /bin/false



RUN true 



RUN echo 'No supported packages' \
    && /bin/false



