FROM kolla/ubuntu-binary-barbican-base:8.0.0
LABEL maintainer="Kolla Project (https://launchpad.net/kolla)" name="barbican-keystone-listener" build-date="20190404"






    
       
    

RUN apt-get update && apt-get -y install --no-install-recommends barbican-keystone-listener && apt-get clean && rm -rf /var/lib/apt/lists/*






USER barbican