FROM kolla/ubuntu-binary-kuryr-base:8.0.0
LABEL maintainer="Kolla Project (https://launchpad.net/kolla)" name="kuryr-libnetwork" build-date="20190404"







RUN echo 'binary not yet available for ubuntu' \
    && /bin/false




