FROM kolla/ubuntu-binary-zun-base:8.0.0
LABEL maintainer="Kolla Project (https://launchpad.net/kolla)" name="zun-api" build-date="20190404"





RUN echo 'binary not yet available for ubuntu' \
    && /bin/false



COPY extend_start.sh /usr/local/bin/kolla_zun_extend_start
RUN chmod 755 /usr/local/bin/kolla_zun_extend_start


