FROM kolla/ubuntu-binary-searchlight-base:8.0.0
LABEL maintainer="Kolla Project (https://launchpad.net/kolla)" name="searchlight-listener" build-date="20190404"





RUN echo 'binary not yet available for ubuntu' \
    && /bin/false






USER searchlight