FROM kolla/ubuntu-binary-vitrage-base:8.0.0
LABEL maintainer="Kolla Project (https://launchpad.net/kolla)" name="vitrage-notifier" build-date="20190404"







    

RUN echo 'binary not yet available for ubuntu' \
    && /bin/false

    






USER vitrage