FROM kolla/ubuntu-binary-base:8.0.0
LABEL maintainer="Kolla Project (https://launchpad.net/kolla)" name="tripleoclient" build-date="20190404"






    
RUN echo 'tripleoclient not yet available for ubuntu' && /bin/false
    



COPY create_super_user.sh /usr/local/bin/create_super_user.sh
RUN chmod 750 /usr/local/bin/create_super_user.sh


