FROM kolla/ubuntu-binary-octavia-base:8.0.0
LABEL maintainer="Kolla Project (https://launchpad.net/kolla)" name="octavia-health-manager" build-date="20190404"






    
RUN echo 'binary not yet available for ubuntu' \
            && /bin/false
    








USER octavia